# Generated by Django 4.1.1 on 2022-09-20 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_subitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subitem',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
